#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  THE ACADEMY — Linux Installer
#  Installs and launches The Academy on any Debian/Ubuntu/Fedora/Arch system.
#  Run with:  bash install-linux.sh
# ═══════════════════════════════════════════════════════════════

set -e

ACADEMY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${CYAN}╔══════════════════════════════════════╗${NC}"
echo -e "${CYAN}║        THE ACADEMY — INSTALLER       ║${NC}"
echo -e "${CYAN}║           Linux Edition              ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════╝${NC}"
echo ""

# ── Step 1: Check for Node.js ──────────────────────────────────
echo -e "${YELLOW}[1/5] Checking for Node.js...${NC}"
if command -v node &>/dev/null; then
    NODE_VERSION=$(node --version | sed 's/v//')
    MAJOR=$(echo "$NODE_VERSION" | cut -d. -f1)
    if [ "$MAJOR" -lt 18 ]; then
        echo -e "${RED}  Node.js $NODE_VERSION found but version 18+ is required.${NC}"
        echo "  Please upgrade: https://nodejs.org"
        exit 1
    fi
    echo -e "${GREEN}  Node.js v$NODE_VERSION found.${NC}"
else
    echo -e "${RED}  Node.js not found. Attempting to install...${NC}"
    if command -v apt-get &>/dev/null; then
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y nodejs
    elif command -v pacman &>/dev/null; then
        sudo pacman -S --noconfirm nodejs npm
    else
        echo -e "${RED}  Could not auto-install Node.js. Please install manually:${NC}"
        echo "  https://nodejs.org/en/download/"
        exit 1
    fi
    echo -e "${GREEN}  Node.js installed.${NC}"
fi

# ── Step 2: Check for npm ──────────────────────────────────────
echo -e "${YELLOW}[2/5] Checking for npm...${NC}"
if ! command -v npm &>/dev/null; then
    echo -e "${RED}  npm not found. Please install Node.js from https://nodejs.org${NC}"
    exit 1
fi
echo -e "${GREEN}  npm $(npm --version) found.${NC}"

# ── Step 3: Install dependencies ──────────────────────────────
echo -e "${YELLOW}[3/5] Installing dependencies...${NC}"
cd "$ACADEMY_DIR"
npm install --prefer-offline 2>&1 | tail -5
echo -e "${GREEN}  Dependencies installed.${NC}"

# ── Step 4: Create .env if missing ───────────────────────────
echo -e "${YELLOW}[4/5] Setting up environment...${NC}"
ENV_FILE="$ACADEMY_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    SESSION_SECRET=$(node -e "const c=require('crypto');console.log(c.randomBytes(32).toString('hex'))")
    cat > "$ENV_FILE" <<EOF
# The Academy — Environment Configuration
# Generated by install-linux.sh on $(date)

SESSION_SECRET=$SESSION_SECRET

# Optional: Add a Neon/PostgreSQL database URL for persistence
# DATABASE_URL=postgresql://user:pass@host/dbname

# Optional: Add an OpenAI API key for AI features
# AI_INTEGRATIONS_OPENAI_API_KEY=sk-...
# AI_INTEGRATIONS_OPENAI_BASE_URL=https://api.openai.com/v1
EOF
    echo -e "${GREEN}  Created .env with generated SESSION_SECRET.${NC}"
else
    echo -e "${GREEN}  .env already exists — skipping.${NC}"
fi

# ── Step 5: Launch ────────────────────────────────────────────
echo -e "${YELLOW}[5/5] Launching The Academy...${NC}"
echo ""
echo -e "${CYAN}  The Academy is starting at: ${GREEN}http://localhost:5000${NC}"
echo -e "${CYAN}  Press Ctrl+C to stop the server.${NC}"
echo ""
npm run dev
