# ═══════════════════════════════════════════════════════════════
#  THE ACADEMY — Windows Installer (PowerShell)
#  Installs and launches The Academy on Windows 10/11.
#  Run with:  Right-click → "Run with PowerShell"
#  Or from PowerShell:  .\install-windows.ps1
# ═══════════════════════════════════════════════════════════════

$ErrorActionPreference = "Stop"
$AcademyDir = Split-Path -Parent $PSScriptRoot

function Write-Header {
    Write-Host ""
    Write-Host "╔══════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║        THE ACADEMY — INSTALLER       ║" -ForegroundColor Cyan
    Write-Host "║          Windows Edition             ║" -ForegroundColor Cyan
    Write-Host "╚══════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host ""
}

function Test-NodeVersion {
    try {
        $version = (node --version 2>$null).TrimStart('v')
        $major = [int]($version.Split('.')[0])
        return @{ Found = $true; Version = $version; Major = $major }
    } catch {
        return @{ Found = $false }
    }
}

Write-Header

# ── Step 1: Check for Node.js ──────────────────────────────────
Write-Host "[1/5] Checking for Node.js..." -ForegroundColor Yellow
$node = Test-NodeVersion
if ($node.Found) {
    if ($node.Major -lt 18) {
        Write-Host "  Node.js $($node.Version) found but version 18+ is required." -ForegroundColor Red
        Write-Host "  Please upgrade from: https://nodejs.org/en/download/" -ForegroundColor Red
        Write-Host ""
        Write-Host "  Press any key to open the Node.js download page..."
        $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
        Start-Process "https://nodejs.org/en/download/"
        exit 1
    }
    Write-Host "  Node.js v$($node.Version) found." -ForegroundColor Green
} else {
    Write-Host "  Node.js not found." -ForegroundColor Red
    Write-Host ""
    Write-Host "  Checking for winget..." -ForegroundColor Yellow
    if (Get-Command winget -ErrorAction SilentlyContinue) {
        Write-Host "  Installing Node.js via winget..." -ForegroundColor Yellow
        winget install OpenJS.NodeJS.LTS --accept-package-agreements --accept-source-agreements
        Write-Host "  Node.js installed. Please CLOSE and REOPEN this window, then run the script again." -ForegroundColor Green
        Write-Host ""
        Write-Host "  Press any key to exit..."
        $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
        exit 0
    } else {
        Write-Host "  Please install Node.js from: https://nodejs.org/en/download/" -ForegroundColor Red
        Write-Host "  After installing, run this script again." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "  Press any key to open the download page..."
        $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
        Start-Process "https://nodejs.org/en/download/"
        exit 1
    }
}

# ── Step 2: Check for npm ──────────────────────────────────────
Write-Host "[2/5] Checking for npm..." -ForegroundColor Yellow
try {
    $npmVersion = npm --version 2>$null
    Write-Host "  npm $npmVersion found." -ForegroundColor Green
} catch {
    Write-Host "  npm not found. Please reinstall Node.js from https://nodejs.org" -ForegroundColor Red
    exit 1
}

# ── Step 3: Install dependencies ──────────────────────────────
Write-Host "[3/5] Installing dependencies..." -ForegroundColor Yellow
Set-Location $AcademyDir
npm install --prefer-offline 2>&1 | Select-Object -Last 5
Write-Host "  Dependencies installed." -ForegroundColor Green

# ── Step 4: Create .env if missing ───────────────────────────
Write-Host "[4/5] Setting up environment..." -ForegroundColor Yellow
$EnvFile = Join-Path $AcademyDir ".env"
if (-not (Test-Path $EnvFile)) {
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $sessionSecret = ($bytes | ForEach-Object { '{0:x2}' -f $_ }) -join ''
    $envContent = @"
# The Academy — Environment Configuration
# Generated by install-windows.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

SESSION_SECRET=$sessionSecret

# Optional: Add a Neon/PostgreSQL database URL for persistence
# DATABASE_URL=postgresql://user:pass@host/dbname

# Optional: Add an OpenAI API key for AI features
# AI_INTEGRATIONS_OPENAI_API_KEY=sk-...
# AI_INTEGRATIONS_OPENAI_BASE_URL=https://api.openai.com/v1
"@
    Set-Content -Path $EnvFile -Value $envContent -Encoding UTF8
    Write-Host "  Created .env with generated SESSION_SECRET." -ForegroundColor Green
} else {
    Write-Host "  .env already exists — skipping." -ForegroundColor Green
}

# ── Step 5: Open browser + launch ────────────────────────────
Write-Host "[5/5] Launching The Academy..." -ForegroundColor Yellow
Write-Host ""
Write-Host "  The Academy is starting at: http://localhost:5000" -ForegroundColor Cyan
Write-Host "  Your browser will open automatically in a few seconds." -ForegroundColor Cyan
Write-Host "  Press Ctrl+C in this window to stop the server." -ForegroundColor Cyan
Write-Host ""

# Auto-open browser after delay
Start-Job -ScriptBlock {
    Start-Sleep -Seconds 5
    Start-Process "http://localhost:5000"
} | Out-Null

npm run dev
